services:
    frontend:
        build:
            context: ./src/frontend
        container_name: frontend-automatic-tests-frontend
        env_file:
            - ./docker/envs/frontend/.env.automatic-tests
        ports:
            - "5004:5173"

    backend:
        build: ./src/backend
        container_name: frontend-automatic-tests-backend
        env_file:
            - ./docker/envs/backend/.env.dev
        ports:
            - "5003:5000"
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-I", "localhost:5000/"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s

    db:
        image: postgres:15
        container_name: frontend-automatic-tests-db
        environment:
            POSTGRES_USER: dwengo-dev
            POSTGRES_PASSWORD: dwengo
            POSTGRES_DB: dwengo-dev
        ports:
            - "5002:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "dwengo-dev"]
            interval: 10s
            retries: 5
