services:
  frontend-prod:
    build:
      context: ./src/frontend
    image: frontend-dwengo
    ports:
      - "8080:5173"
    env_file:
      - ./docker/envs/frontend/.env.prod
    depends_on:
      - backend-prod

  backend-prod:
    build:
      context: ./src/backend/backend_opzet
    image: backend-dwengo
    ports:
      - "2197:2197"
    env_file:
      - ./docker/envs/backend/.env.prod
    extra_hosts:
      - "host.docker.internal:10.10.0.0" # TODO: pas aan naar correcte waarde

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24 # zorgt dat er geen conflicterende IPs zijn met intern netwerk
