services:
  backend:
    build: ./src/backend/backend_opzet
    container_name: backend
    env_file:
      - ./docker/envs/backend/.env.dev
    ports:
      - "2197:2197"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./src/frontend
    container_name: frontend
    env_file:
      - ./docker/envs/frontend/.env.dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: dwengo-dev
      POSTGRES_PASSWORD: dwengo
      POSTGRES_DB: dwengo-dev
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "dwengo-dev"]
      interval: 10s
      retries: 5

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
