#Node image gebruiken
FROM node:18

# Working directory opzetten
WORKDIR /app

# Dependencies installeren
COPY package*.json ./
RUN npm install

# Code kopiëren
COPY . .

# Poort 8080 openen
EXPOSE 8080

# Start frontend server
CMD npm start

