name: Deploy on push to staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
    types:
      - closed
  workflow_dispatch:

jobs:
  execute-script:
    if: github.event_name == 'push' || github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure staging branch is available
        run: |
          git fetch --all --prune
          git reset --hard origin/staging  # Discard local changes
          git checkout staging
          git pull --force origin staging  # Ensure latest remote changes

      - name: Execute deployment script
        run: |
          APP_DIR="/home/selab2/dwengo"
          DOCKER_COMPOSE_FILE="stage-docker-compose.yml"

          echo "Stopping current deployment..."
          cd $APP_DIR
          docker-compose -f $DOCKER_COMPOSE_FILE down -v

          echo "Building and deploying with Docker Compose..."
          cd $APP_DIR
          docker-compose -f $DOCKER_COMPOSE_FILE up --build -d || { echo "Docker Compose failed"; exit 1; }

          echo "Deployment complete!"
