name: Deploy on push to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      

jobs:
  execute-script:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute deployment script
        run: |
          APP_DIR="/home/selab2/dwengo"
          DOCKER_COMPOSE_FILE="deploy-docker-compose.yml"

          echo "Pulling latest code..."
          cd $APP_DIR
          git checkout main
          git pull --force git@github.com:SELab-2/Dwengo-5.git || { echo "Git pull failed"; exit 1; }

          cd $APP_DIR
          docker-compose -f $DOCKER_COMPOSE_FILE down -v

          echo "Building and deploying with Docker Compose..."
          cd $APP_DIR
          docker-compose -f $DOCKER_COMPOSE_FILE up --build -d || { echo "Docker Compose failed"; exit 1; }

          echo "Deployment complete!"
