name: Deploy on push to main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
      

jobs:
  execute-script:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute deployment script
        run: |
          /home/selab2/deploy.sh
