name: Deploy Staging on Update

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Staging Branch
        uses: actions/checkout@v4

      - name: Run Deployment Script
        run: |
          /home/selab2/stage.sh
