name: Merge dev to main weekly

on:
  schedule:
    - cron: "0 4 * * 1"

  workflow_dispatch:

jobs:
  merge-branches:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"

      - name: Fetch Latest Changes
        run: |
          git fetch --all

      - name: Force main to match dev
        run: |
            git checkout main
            git reset --hard origin/dev
            git push --force origin main
  
